const data = {
  products: [
    {
      _id: '1',
      name: 'Nurse Pin',
      category: 'pin',
      image: '/images/p1.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Doctor Pin',
      category: 'pin',
      image: '/images/p2.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Law Pin',
      category: 'pin',
      image: '/images/p3.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Chimstry Pin',
      category: 'pin',
      image: '/images/p4.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Dentist Pin',
      category: 'pin',
      image: '/images/p5.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Art Pin',
      category: 'pin',
      image: '/images/p6.jpg',
      price: 10,
      brand: 'SheIn',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;